# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necessity',
            name='interval',
        ),
        migrations.AddField(
            model_name='necessity',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
